### ISSUE TITLE
failure on ignored python file - should respect excludes?

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [asottile/seed-isort-config#8]
with a pre-commit config of 
```yaml
exclude: ^(data|sprout)/
repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.0.1
  hooks:
  - id: seed-isort-config
```
i observe

```
seed isort known_third_party.............................................Failed
hookid: seed-isort-config

Traceback (most recent call last):
  File "/home/rpfannsc/.cache/pre-commit/repomfmabho9/py_env-python3/bin/seed-isort-config", line 11, in <module>
    sys.exit(main())
  File "/home/rpfannsc/.cache/pre-commit/repomfmabho9/py_env-python3/lib/python3.6/site-packages/seed_isort_config.py", line 67, in main
    third_party = ','.join(sorted(third_party_imports(filenames, appdirs)))
  File "/home/rpfannsc/.cache/pre-commit/repomfmabho9/py_env-python3/lib/python3.6/site-packages/seed_isort_config.py", line 45, in third_party_imports
    visitor.visit(ast.parse(f.read(), filename=filename))
  File "/usr/lib64/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "data/bundles/merkyl/__init__.py", line 13
    print "allowed.files not found, exiting"
                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("allowed.files not found, exiting")?
```

unfortunately its not clear how to fix since the tool has to scan the folders

**Comment by asottile** [comment]
Not sure there's a clear fix for this one, probably going to wontfix

**Comment by asottile** [comment]
Actually, Hmmm, maybe a cli argument would work?

**Comment by RonnyPfannschmidt** [comment]
@asottile actually - how about just ignoring unusable files while printing a warning?

**Comment by asottile** [comment]
That could work too, though I imagine exclusion would be slightly more powerful and less error prone
